In [1]:
from datetime import datetime
import MetaTrader5 as mt5
import pandas as pd
import pytz
import time
import pandas_ta as pta
import matplotlib.pyplot as plt 
import threading

# import threading
mt5.initialize()

True

In [2]:
def price_action(symbol, lot, ask, bid, order_type):
    buy_profit=mt5.order_calc_profit(order_type,symbol,lot,ask,bid)
    return buy_profit
price_action("EURUSD", 0.02, 1.18969, 1.17030,mt5.ORDER_TYPE_SELL)

38.78

In [3]:
def get_values(symbol):
    timezone = pytz.timezone("Etc/UTC")
    x = datetime.now()
    utc_from = datetime(x.year, x.month, 1, tzinfo=timezone)
    utc_to = datetime(x.year, x.month, x.day+1, tzinfo=timezone)
    rates = mt5.copy_rates_range(symbol, mt5.TIMEFRAME_H1, utc_from, utc_to)

    rates_frame = pd.DataFrame(rates)
#     rates_frame = rates_frame.iloc[-150:]
    rates_frame = rates_frame.drop(['tick_volume', 'spread', 'real_volume'], axis=1)
    # convert time in seconds into the datetime format
    rates_frame['clsma']= rates_frame['close'].rolling(window=8).mean()
    rates_frame['smaC']= rates_frame['clsma'].rolling(window=8).mean()


    rates_frame['clsma']= rates_frame['open'].rolling(window=8).mean()
    rates_frame['smaO']= rates_frame['clsma'].rolling(window=8).mean()

    rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
    rates_frame = rates_frame.set_index('time')
    rates_frame = rates_frame.drop(['high', 'low', 'clsma'], axis=1)
    return rates_frame

In [4]:
global global_loss
global profit
global conti


profit = []

global_loss = []
symbol = "EURGBP"
b = get_values(symbol)
b = b.dropna()
b

                        open    close      smaC      smaO
time
2021-08-02 14:00:00  0.85538  0.85530  0.853917  0.853842
2021-08-02 15:00:00  0.85530  0.85471  0.853977  0.853919
2021-08-02 16:00:00  0.85471  0.85407  0.854046  0.853978
2021-08-02 17:00:00  0.85414  0.85460  0.854124  0.854048
2021-08-02 18:00:00  0.85462  0.85503  0.854227  0.854127
...                      ...      ...       ...       ...
2021-08-27 19:00:00  0.85655  0.85643  0.857531  0.857689
2021-08-27 20:00:00  0.85643  0.85666  0.857375  0.857535
2021-08-27 21:00:00  0.85666  0.85658  0.857206  0.857378
2021-08-27 22:00:00  0.85658  0.85697  0.857051  0.857207
2021-08-27 23:00:00  0.85701  0.85683  0.856931  0.857052

[466 rows x 4 columns]

In [10]:
global global_loss
global profit
global conti


profit = []

global_loss = []
symbol = "EURUSD"
a= get_values(symbol)
a = a.dropna()
a

                        open    close      smaC      smaO
time
2021-08-02 14:00:00  1.18910  1.18900  1.187420  1.187230
2021-08-02 15:00:00  1.18901  1.18729  1.187623  1.187433
2021-08-02 16:00:00  1.18730  1.18807  1.187830  1.187635
2021-08-02 17:00:00  1.18832  1.18783  1.188008  1.187845
2021-08-02 18:00:00  1.18784  1.18725  1.188147  1.188026
...                      ...      ...       ...       ...
2021-08-27 19:00:00  1.17934  1.18003  1.176224  1.176047
2021-08-27 20:00:00  1.18001  1.17946  1.176446  1.176221
2021-08-27 21:00:00  1.17946  1.17940  1.176714  1.176440
2021-08-27 22:00:00  1.17940  1.17962  1.177030  1.176704
2021-08-27 23:00:00  1.17959  1.17926  1.177416  1.177017

[466 rows x 4 columns]

In [11]:
def follow(j, a, buy_price, order_type):
    loss = 0.0
    g = 0
    for k in range(j+1, len(a)):
        sell_price = a.iloc[k].close
        pp = price_action(symbol, 0.02, buy_price, sell_price, order_type)
        if pp > 1.0:
            profit.append(pp)
            global_loss.append(loss)
            break
        elif pp < 0.0:
            if pp < loss:
                loss = pp
    if k == len(a)-1:
        conti.append([pp, a.iloc[j-1].name])

In [25]:
#less negatives more positives
# symbol = "CADJPY"
# b= get_values1(symbol)
# b = b.dropna()
b = a
B = []
check = 0
profit = []
index = []
indexB = []
counter = 0
peck = 0
p= []
checks = 0
counterr = 0
profits = []
up = 0
rsi1 = []
rsi2 = []
mul = 100000
global_loss = []
conti = []

for i in range(2,len(a)):
    if a.iloc[i-1].smaC < a.iloc[i-1].smaO and check == 0:
        if checks == 1:
            print("BREAK")
            sell_price = a.iloc[i].close
            pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
            print(f"BUY_price--->{buy_price}")
            print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
            checks = 0
            profit.append(pp)
            print(profit[-1])
        buy_price = a.iloc[i].open #SELL Action
        print("#"*20)
        print("SELL")
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        check = 1
        checks = 0
    if check == 1:
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
        if pp > 1.0:
            check = 0
            profit.append(pp)
    if a.iloc[i-1].smaC > a.iloc[i-1].smaO and checks == 0:
        if check == 1:
            sell_price = a.iloc[i].close
            pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
            print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
            check = 0
            profit.append(pp)
        buy_price = a.iloc[i].open #BUY Action
        print("#"*20)
        print("BUY")
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        checks = 1
        check = 0
    if checks == 1:
        print("checks")
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
        if pp > 1.0:
            check = 0
            profit.append(pp)

####################
BUY
2021-08-02 16:00:00
1.1873
********************
checks
-1.54-----1.18807--2021-08-02 16:00:00
checks
-1.06-----1.18783--2021-08-02 17:00:00
checks
0.1-----1.18725--2021-08-02 18:00:00
checks
0.8-----1.1869--2021-08-02 19:00:00
checks
1.12-----1.18674--2021-08-02 20:00:00
BREAK
BUY_price--->1.1873
-0.06-----1.18733--2021-08-02 21:00:00
-0.06
####################
SELL
2021-08-02 21:00:00
1.18672
********************
-1.22-----1.18733--2021-08-02 21:00:00
-0.6-----1.18702--2021-08-02 22:00:00
0.54-----1.18645--2021-08-02 23:00:00
-0.3-----1.18687--2021-08-03 00:00:00
-1.26-----1.18735--2021-08-03 01:00:00
-1.22-----1.18733--2021-08-03 02:00:00
-0.8-----1.18712--2021-08-03 03:00:00
-1.4-----1.18742--2021-08-03 04:00:00
-0.6-----1.18702--2021-08-03 05:00:00
-1.34-----1.18739--2021-08-03 06:00:00
-2.5-----1.18797--2021-08-03 07:00:00
-1.42-----1.18743--2021-08-03 08:00:00
-1.02-----1.18723--2021-08-03 09:00:00
-1.02-----1.18723--2021-08-03 09:00:00
####################
BUY
2021-08-03 09:00:00
1.1874500000000001
********************
checks
0.44-----1.18723--2021-08-03 09:00:00
checks
-0.66-----1.18778--2021-08-03 10:00:00
checks
-1.74-----1.18832--2021-08-03 11:00:00
checks
-1.94-----1.18842--2021-08-03 12:00:00
checks
-2.52-----1.18871--2021-08-03 13:00:00
checks
-3.52-----1.18921--2021-08-03 14:00:00
checks
-2.18-----1.18854--2021-08-03 15:00:00
checks
1.16-----1.18687--2021-08-03 16:00:00
checks
3.26-----1.18582--2021-08-03 17:00:00
checks
3.26-----1.18582--2021-08-03 18:00:00
checks
1.34-----1.18678--2021-08-03 19:00:00
BREAK
BUY_price--->1.1874500000000001
2.3-----1.1863--2021-08-03 20:00:00
2.3
####################
SELL
2021-08-03 20:00:00
1.18679
********************
0.98-----1.1863--2021-08-03 20:00:00
1.24-----1.18617--2021-08-03 21:00:00
####################
SELL
2021-08-03 22:00:00
1.18617
********************
-0.7-----1.18652--2021-08-03 22:00:00
0.5-----1.18592--2021-08-03 23:00:00
-0.02-----1.18618--2021-08-04 00:00:00
-1.32-----1.18683--2021-08-04 01:00:00
-1.3599999999999999-----1.18685--2021-08-04 02:00:00
0.14-----1.1861--2021-08-04 03:00:00
-1.58-----1.18696--2021-08-04 04:00:00
-2.16-----1.18725--2021-08-04 05:00:00
-2.18-----1.18726--2021-08-04 06:00:00
-1.78-----1.18706--2021-08-04 07:00:00
-1.78-----1.18706--2021-08-04 07:00:00
####################
BUY
2021-08-04 07:00:00
1.18727
********************
checks
0.42-----1.18706--2021-08-04 07:00:00
checks
0.3-----1.18712--2021-08-04 08:00:00
checks
-1.1400000000000001-----1.18784--2021-08-04 09:00:00
checks
-0.72-----1.18763--2021-08-04 10:00:00
checks
4.52-----1.1850100000000001--2021-08-04 11:00:00
checks
2.92-----1.18581--2021-08-04 12:00:00
checks
3.44-----1.18555--2021-08-04 13:00:00
checks
1.98-----1.18628--2021-08-04 14:00:00
BREAK
BUY_price--->1.18727
-3.2800000000000002-----1.18891--2021-08-04 15:00:00
-3.2800000000000002
####################
SELL
2021-08-04 15:00:00
1.18626
********************
-5.3-----1.18891--2021-08-04 15:00:00
-6.08-----1.1893--2021-08-04 16:00:00
4.12-----1.1842--2021-08-04 17:00:00
####################
BUY
2021-08-04 17:00:00
1.18922
********************
checks
10.04-----1.1842--2021-08-04 17:00:00
BREAK
BUY_price--->1.18922
10.2-----1.18412--2021-08-04 18:00:00
10.2
####################
SELL
2021-08-04 18:00:00
1.18425
********************
0.26-----1.18412--2021-08-04 18:00:00
1.12-----1.18369--2021-08-04 19:00:00
####################
SELL
2021-08-04 20:00:00
1.18371
********************
-0.2-----1.18381--2021-08-04 20:00:00
-0.14-----1.18378--2021-08-04 21:00:00
0.06-----1.18368--2021-08-04 22:00:00
1.12-----1.18315--2021-08-04 23:00:00
####################
SELL
2021-08-05 00:00:00
1.18358
********************
0.2-----1.18348--2021-08-05 00:00:00
-0.28-----1.18372--2021-08-05 01:00:00
-0.08-----1.18362--2021-08-05 02:00:00
0.98-----1.18309--2021-08-05 03:00:00
0.18-----1.18349--2021-08-05 04:00:00
0.18-----1.18349--2021-08-05 05:00:00
0.58-----1.18329--2021-08-05 06:00:00
0.1-----1.18353--2021-08-05 07:00:00
0.06-----1.1835499999999999--2021-08-05 08:00:00
-0.16-----1.18366--2021-08-05 09:00:00
-2.48-----1.18482--2021-08-05 10:00:00
-0.06-----1.18361--2021-08-05 11:00:00
0.92-----1.18312--2021-08-05 12:00:00
-1.92-----1.18454--2021-08-05 13:00:00
-3.7800000000000002-----1.18547--2021-08-05 14:00:00
-3.7800000000000002-----1.18547--2021-08-05 14:00:00
####################
BUY
2021-08-05 14:00:00
1.18452
********************
checks
-1.9-----1.18547--2021-08-05 14:00:00
checks
2.04-----1.1835--2021-08-05 15:00:00
checks
1.52-----1.18376--2021-08-05 16:00:00
checks
1.38-----1.18383--2021-08-05 17:00:00
checks
1.74-----1.18365--2021-08-05 18:00:00
checks
1.38-----1.18383--2021-08-05 19:00:00
checks
2.12-----1.18346--2021-08-05 20:00:00
checks
2.1-----1.18347--2021-08-05 21:00:00
checks
2.04-----1.1835--2021-08-05 22:00:00
BREAK
BUY_price--->1.18452
3.46-----1.18279--2021-08-05 23:00:00
3.46
####################
SELL
2021-08-05 23:00:00
1.18351
********************
1.44-----1.18279--2021-08-05 23:00:00
####################
SELL
2021-08-06 00:00:00
1.18311
********************
-0.22-----1.18322--2021-08-06 00:00:00
-0.1-----1.18316--2021-08-06 01:00:00
-0.2-----1.18321--2021-08-06 02:00:00
1.3599999999999999-----1.18243--2021-08-06 03:00:00
####################
SELL
2021-08-06 04:00:00
1.18245
********************
-0.1-----1.1825--2021-08-06 04:00:00
0.86-----1.18202--2021-08-06 05:00:00
0.5-----1.1822--2021-08-06 06:00:00
0.04-----1.18243--2021-08-06 07:00:00
0.18-----1.18236--2021-08-06 08:00:00
-0.48-----1.18269--2021-08-06 09:00:00
0.28-----1.18231--2021-08-06 10:00:00
2.94-----1.18098--2021-08-06 11:00:00
####################
SELL
2021-08-06 12:00:00
1.18099
********************
0.26-----1.18086--2021-08-06 12:00:00
1.32-----1.18033--2021-08-06 13:00:00
####################
SELL
2021-08-06 14:00:00
1.18034
********************
-0.46-----1.18057--2021-08-06 14:00:00
4.14-----1.17827--2021-08-06 15:00:00
####################
SELL
2021-08-06 16:00:00
1.17826
********************
2.06-----1.17723--2021-08-06 16:00:00
####################
SELL
2021-08-06 17:00:00
1.17729
********************
2.74-----1.17592--2021-08-06 17:00:00
####################
SELL
2021-08-06 18:00:00
1.17591
********************
0.16-----1.17583--2021-08-06 18:00:00
1.04-----1.17539--2021-08-06 19:00:00
####################
SELL
2021-08-06 20:00:00
1.17538
********************
-0.82-----1.1757900000000001--2021-08-06 20:00:00
-0.22-----1.17549--2021-08-06 21:00:00
-0.74-----1.17575--2021-08-06 22:00:00
-0.68-----1.17572--2021-08-06 23:00:00
-0.52-----1.17564--2021-08-09 00:00:00
0.32-----1.17522--2021-08-09 01:00:00
1.7-----1.17453--2021-08-09 02:00:00
####################
SELL
2021-08-09 03:00:00
1.17453
********************
-0.62-----1.17484--2021-08-09 03:00:00
-1.3-----1.1751800000000001--2021-08-09 04:00:00
-2.56-----1.17581--2021-08-09 05:00:00
-2.34-----1.1757--2021-08-09 06:00:00
-3.18-----1.17612--2021-08-09 07:00:00
-2.12-----1.17559--2021-08-09 08:00:00
-2.34-----1.1757--2021-08-09 09:00:00
-2.04-----1.17555--2021-08-09 10:00:00
-1.5-----1.1752799999999999--2021-08-09 11:00:00
-2.8-----1.17593--2021-08-09 12:00:00
-2.8-----1.17593--2021-08-09 12:00:00
####################
BUY
2021-08-09 12:00:00
1.17527
********************
checks
-1.32-----1.17593--2021-08-09 12:00:00
checks
0.22-----1.17516--2021-08-09 13:00:00
checks
-1.62-----1.17608--2021-08-09 14:00:00
checks
-1.24-----1.1758899999999999--2021-08-09 15:00:00
checks
-1.3599999999999999-----1.17595--2021-08-09 16:00:00
checks
2.08-----1.17423--2021-08-09 17:00:00
checks
1.28-----1.17463--2021-08-09 18:00:00
BREAK
BUY_price--->1.17527
2.5-----1.17402--2021-08-09 19:00:00
2.5
####################
SELL
2021-08-09 19:00:00
1.17463
********************
1.22-----1.17402--2021-08-09 19:00:00
####################
SELL
2021-08-09 20:00:00
1.174
********************
-0.26-----1.17413--2021-08-09 20:00:00
0.36-----1.17382--2021-08-09 21:00:00
1.4-----1.1733--2021-08-09 22:00:00
####################
SELL
2021-08-09 23:00:00
1.17331
********************
0.0-----1.17331--2021-08-09 23:00:00
-0.28-----1.1734499999999999--2021-08-10 00:00:00
-0.38-----1.1735--2021-08-10 01:00:00
-0.18-----1.1734--2021-08-10 02:00:00
-0.48-----1.17355--2021-08-10 03:00:00
0.48-----1.17307--2021-08-10 04:00:00
-0.58-----1.1736--2021-08-10 05:00:00
-0.76-----1.1736900000000001--2021-08-10 06:00:00
-0.62-----1.17362--2021-08-10 07:00:00
-0.46-----1.17354--2021-08-10 08:00:00
-0.72-----1.17367--2021-08-10 09:00:00
0.74-----1.17294--2021-08-10 10:00:00
0.62-----1.173--2021-08-10 11:00:00
2.32-----1.17215--2021-08-10 12:00:00
####################
SELL
2021-08-10 13:00:00
1.17216
********************
-0.48-----1.1724--2021-08-10 13:00:00
0.3-----1.17201--2021-08-10 14:00:00
1.54-----1.17139--2021-08-10 15:00:00
####################
SELL
2021-08-10 16:00:00
1.1714
********************
-0.06-----1.17143--2021-08-10 16:00:00
-0.62-----1.17171--2021-08-10 17:00:00
-0.86-----1.17183--2021-08-10 18:00:00
0.08-----1.17136--2021-08-10 19:00:00
-0.42-----1.17161--2021-08-10 20:00:00
-1.28-----1.17204--2021-08-10 21:00:00
-0.48-----1.17164--2021-08-10 22:00:00
0.28-----1.17126--2021-08-10 23:00:00
-0.46-----1.17163--2021-08-11 00:00:00
-1.06-----1.17193--2021-08-11 01:00:00
-0.7-----1.17175--2021-08-11 02:00:00
0.6-----1.1711--2021-08-11 03:00:00
-0.98-----1.1718899999999999--2021-08-11 04:00:00
-1.8-----1.1723--2021-08-11 05:00:00
-0.5-----1.17165--2021-08-11 06:00:00
-0.38-----1.17159--2021-08-11 07:00:00
-0.26-----1.17153--2021-08-11 08:00:00
1.34-----1.17073--2021-08-11 09:00:00
####################
SELL
2021-08-11 10:00:00
1.17072
********************
-0.68-----1.17106--2021-08-11 10:00:00
-0.64-----1.17104--2021-08-11 11:00:00
-0.28-----1.17086--2021-08-11 12:00:00
-1.06-----1.1712500000000001--2021-08-11 13:00:00
-1.3-----1.17137--2021-08-11 14:00:00
-5.5-----1.17347--2021-08-11 15:00:00
-4.96-----1.1732--2021-08-11 16:00:00
-5.96-----1.1737--2021-08-11 17:00:00
-5.5-----1.17347--2021-08-11 18:00:00
-5.5-----1.17347--2021-08-11 18:00:00
####################
BUY
2021-08-11 18:00:00
1.1737
********************
checks
0.46-----1.17347--2021-08-11 18:00:00
checks
-1.88-----1.17464--2021-08-11 19:00:00
checks
-1.76-----1.17458--2021-08-11 20:00:00
checks
0.04-----1.17368--2021-08-11 21:00:00
checks
-0.72-----1.1740599999999999--2021-08-11 22:00:00
checks
0.68-----1.17336--2021-08-11 23:00:00
checks
-0.2-----1.1738--2021-08-12 00:00:00
checks
-0.6-----1.174--2021-08-12 01:00:00
checks
-0.62-----1.17401--2021-08-12 02:00:00
checks
-0.3-----1.17385--2021-08-12 03:00:00
checks
-0.26-----1.17383--2021-08-12 04:00:00
checks
-0.08-----1.17374--2021-08-12 05:00:00
checks
-1.12-----1.17426--2021-08-12 06:00:00
BREAK
BUY_price--->1.1737
-0.22-----1.17381--2021-08-12 07:00:00
-0.22
####################
SELL
2021-08-12 07:00:00
1.17428
********************
0.94-----1.17381--2021-08-12 07:00:00
0.62-----1.17397--2021-08-12 08:00:00
1.76-----1.1734--2021-08-12 09:00:00
####################
SELL
2021-08-12 10:00:00
1.1734
********************
-1.24-----1.17402--2021-08-12 10:00:00
-2.24-----1.17452--2021-08-12 11:00:00
-1.2-----1.174--2021-08-12 12:00:00
-0.02-----1.17341--2021-08-12 13:00:00
-0.02-----1.17341--2021-08-12 13:00:00
####################
BUY
2021-08-12 13:00:00
1.174
********************
checks
1.18-----1.17341--2021-08-12 13:00:00
checks
0.64-----1.17368--2021-08-12 14:00:00
BREAK
BUY_price--->1.174
0.34-----1.17383--2021-08-12 15:00:00
0.34
####################
SELL
2021-08-12 15:00:00
1.17367
********************
-0.32-----1.17383--2021-08-12 15:00:00
1.78-----1.17278--2021-08-12 16:00:00
####################
SELL
2021-08-12 17:00:00
1.17276
********************
-0.04-----1.17278--2021-08-12 17:00:00
-1.12-----1.17332--2021-08-12 18:00:00
-1.78-----1.17365--2021-08-12 19:00:00
-1.74-----1.17363--2021-08-12 20:00:00
-0.16-----1.1728399999999999--2021-08-12 21:00:00
-1.18-----1.1733500000000001--2021-08-12 22:00:00
0.04-----1.1727400000000001--2021-08-12 23:00:00
-0.26-----1.17289--2021-08-13 00:00:00
-1.3599999999999999-----1.17344--2021-08-13 01:00:00
-1.32-----1.17342--2021-08-13 02:00:00
-1.3599999999999999-----1.17344--2021-08-13 03:00:00
-2.02-----1.17377--2021-08-13 04:00:00
-2.3-----1.17391--2021-08-13 05:00:00
-2.06-----1.17379--2021-08-13 06:00:00
-1.96-----1.17374--2021-08-13 07:00:00
-1.96-----1.17374--2021-08-13 07:00:00
####################
BUY
2021-08-13 07:00:00
1.1738
********************
checks
0.12-----1.17374--2021-08-13 07:00:00
checks
0.56-----1.17352--2021-08-13 08:00:00
checks
1.34-----1.17313--2021-08-13 09:00:00
checks
1.02-----1.17329--2021-08-13 10:00:00
checks
-0.54-----1.17407--2021-08-13 11:00:00
checks
-1.98-----1.17479--2021-08-13 12:00:00

checks
-1.88-----1.17474--2021-08-13 13:00:00
checks
-4.06-----1.17583--2021-08-13 14:00:00
checks
-5.36-----1.17648--2021-08-13 15:00:00
checks
-5.42-----1.17651--2021-08-13 16:00:00
checks
-10.86-----1.17923--2021-08-13 17:00:00
checks
-11.7-----1.17965--2021-08-13 18:00:00
checks
-12.62-----1.18011--2021-08-13 19:00:00
checks
-12.4-----1.18--2021-08-13 20:00:00
checks
-11.74-----1.17967--2021-08-13 21:00:00
checks
-12.22-----1.17991--2021-08-13 22:00:00
checks
-10.74-----1.17917--2021-08-13 23:00:00
checks
-11.06-----1.17933--2021-08-16 00:00:00
checks
-11.26-----1.17943--2021-08-16 01:00:00
checks
-11.4-----1.1795--2021-08-16 02:00:00
checks
-11.74-----1.17967--2021-08-16 03:00:00
checks
-12.2-----1.1799--2021-08-16 04:00:00
checks
-11.84-----1.17972--2021-08-16 05:00:00
checks
-10.62-----1.17911--2021-08-16 06:00:00
checks
-11.32-----1.17946--2021-08-16 07:00:00
BREAK
BUY_price--->1.1738
-9.88-----1.17874--2021-08-16 08:00:00
-9.88
####################
SELL
2021-08-16 08:00:00
1.17946
********************
1.44-----1.17874--2021-08-16 08:00:00
####################
SELL
2021-08-16 09:00:00
1.17875
********************
0.38-----1.17856--2021-08-16 09:00:00
1.32-----1.17809--2021-08-16 10:00:00
####################
SELL
2021-08-16 11:00:00
1.1781
********************
-1.24-----1.17872--2021-08-16 11:00:00
-0.06-----1.17813--2021-08-16 12:00:00
0.0-----1.1781--2021-08-16 13:00:00
2.7199999999999998-----1.1767400000000001--2021-08-16 14:00:00
####################
SELL
2021-08-16 15:00:00
1.17671
********************
-1.8599999999999999-----1.17764--2021-08-16 15:00:00
-1.42-----1.17742--2021-08-16 16:00:00
-3.98-----1.1787--2021-08-16 17:00:00
-1.46-----1.17744--2021-08-16 18:00:00
-1.48-----1.1774499999999999--2021-08-16 19:00:00
-1.8599999999999999-----1.17764--2021-08-16 20:00:00
-1.48-----1.1774499999999999--2021-08-16 21:00:00
-2.04-----1.17773--2021-08-16 22:00:00
-1.1-----1.17726--2021-08-16 23:00:00
-1.72-----1.17757--2021-08-17 00:00:00
-2.24-----1.17783--2021-08-17 01:00:00
-2.04-----1.17773--2021-08-17 02:00:00
-1.28-----1.1773500000000001--2021-08-17 03:00:00
-1.26-----1.17734--2021-08-17 04:00:00
-1.0-----1.17721--2021-08-17 05:00:00
-0.18-----1.1768--2021-08-17 06:00:00
-0.2-----1.17681--2021-08-17 07:00:00
-0.56-----1.17699--2021-08-17 08:00:00
1.22-----1.1761--2021-08-17 09:00:00
####################
SELL
2021-08-17 10:00:00
1.1761
********************
-2.16-----1.17718--2021-08-17 10:00:00
-3.1-----1.17765--2021-08-17 11:00:00
-2.04-----1.17712--2021-08-17 12:00:00
-1.08-----1.17664--2021-08-17 13:00:00
-0.22-----1.17621--2021-08-17 14:00:00
3.52-----1.17434--2021-08-17 15:00:00
####################
SELL
2021-08-17 16:00:00
1.17435
********************
1.2-----1.17375--2021-08-17 16:00:00
####################
SELL
2021-08-17 17:00:00
1.17374
********************
4.12-----1.17168--2021-08-17 17:00:00
####################
SELL
2021-08-17 18:00:00
1.17167
********************
0.8-----1.17127--2021-08-17 18:00:00
1.7-----1.17082--2021-08-17 19:00:00
####################
SELL
2021-08-17 20:00:00
1.17082
********************
-1.88-----1.17176--2021-08-17 20:00:00
-0.48-----1.17106--2021-08-17 21:00:00
-0.64-----1.17114--2021-08-17 22:00:00
0.38-----1.17063--2021-08-17 23:00:00
-0.26-----1.17095--2021-08-18 00:00:00
0.58-----1.17053--2021-08-18 01:00:00
-0.12-----1.17088--2021-08-18 02:00:00
-0.72-----1.17118--2021-08-18 03:00:00
-1.56-----1.1716--2021-08-18 04:00:00
-2.2-----1.17192--2021-08-18 05:00:00
-1.6-----1.1716199999999999--2021-08-18 06:00:00
-1.94-----1.17179--2021-08-18 07:00:00
-1.38-----1.17151--2021-08-18 08:00:00
-1.7-----1.17167--2021-08-18 09:00:00
-3.04-----1.17234--2021-08-18 10:00:00
-3.04-----1.17234--2021-08-18 10:00:00
####################
BUY
2021-08-18 10:00:00
1.17168
********************
checks
-1.32-----1.17234--2021-08-18 10:00:00
checks
-0.6-----1.17198--2021-08-18 11:00:00
checks
0.3-----1.17153--2021-08-18 12:00:00
checks
1.02-----1.17117--2021-08-18 13:00:00
checks
-0.98-----1.17217--2021-08-18 14:00:00
checks
-0.06-----1.17171--2021-08-18 15:00:00
checks
-0.26-----1.17181--2021-08-18 16:00:00
checks
1.1400000000000001-----1.17111--2021-08-18 17:00:00
checks
3.14-----1.17011--2021-08-18 18:00:00
BREAK
BUY_price--->1.17168
3.6-----1.16988--2021-08-18 19:00:00
3.6
####################
SELL
2021-08-18 19:00:00
1.17011
********************
0.46-----1.16988--2021-08-18 19:00:00
0.32-----1.16995--2021-08-18 20:00:00
-2.2-----1.17121--2021-08-18 21:00:00
-2.26-----1.17124--2021-08-18 22:00:00
-1.3-----1.17076--2021-08-18 23:00:00
-1.62-----1.17092--2021-08-19 00:00:00
-2.38-----1.1713--2021-08-19 01:00:00
-0.24-----1.17023--2021-08-19 02:00:00
2.84-----1.16869--2021-08-19 03:00:00
####################
SELL
2021-08-19 04:00:00
1.1687
********************
0.62-----1.16839--2021-08-19 04:00:00
2.1-----1.16765--2021-08-19 05:00:00
####################
SELL
2021-08-19 06:00:00
1.16764
********************
0.3-----1.16749--2021-08-19 06:00:00
-0.02-----1.16765--2021-08-19 07:00:00
0.88-----1.1672--2021-08-19 08:00:00
-0.38-----1.16783--2021-08-19 09:00:00
-1.2-----1.16824--2021-08-19 10:00:00
-2.04-----1.16866--2021-08-19 11:00:00
-3.88-----1.16958--2021-08-19 12:00:00
-3.26-----1.16927--2021-08-19 13:00:00
-4.54-----1.16991--2021-08-19 14:00:00
-4.38-----1.16983--2021-08-19 15:00:00
-4.68-----1.16998--2021-08-19 16:00:00
-1.18-----1.1682299999999999--2021-08-19 17:00:00
-1.18-----1.1682299999999999--2021-08-19 17:00:00
####################
BUY
2021-08-19 17:00:00
1.16998
********************
checks
3.5-----1.1682299999999999--2021-08-19 17:00:00
checks
1.48-----1.16924--2021-08-19 18:00:00
checks
2.38-----1.16879--2021-08-19 19:00:00
checks
4.52-----1.16772--2021-08-19 20:00:00
checks
4.9-----1.16753--2021-08-19 21:00:00
checks
4.7-----1.16763--2021-08-19 22:00:00
checks
5.36-----1.1673--2021-08-19 23:00:00
BREAK
BUY_price--->1.16998
4.52-----1.16772--2021-08-20 00:00:00
4.52
####################
SELL
2021-08-20 00:00:00
1.1676199999999999
********************
-0.2-----1.16772--2021-08-20 00:00:00
-0.24-----1.16774--2021-08-20 01:00:00
0.04-----1.1676--2021-08-20 02:00:00
-1.1400000000000001-----1.16819--2021-08-20 03:00:00
-0.62-----1.16793--2021-08-20 04:00:00
-0.58-----1.16791--2021-08-20 05:00:00
-1.76-----1.1685--2021-08-20 06:00:00
-1.9-----1.1685699999999999--2021-08-20 07:00:00
-2.08-----1.16866--2021-08-20 08:00:00
-1.3-----1.16827--2021-08-20 09:00:00
-0.58-----1.16791--2021-08-20 10:00:00
-0.58-----1.16791--2021-08-20 10:00:00
####################
BUY
2021-08-20 10:00:00
1.16827
********************
checks
0.72-----1.16791--2021-08-20 10:00:00
checks
1.8199999999999998-----1.16736--2021-08-20 11:00:00
checks
1.48-----1.16753--2021-08-20 12:00:00
checks
0.5-----1.16802--2021-08-20 13:00:00
checks
2.98-----1.16678--2021-08-20 14:00:00
BREAK
BUY_price--->1.16827
2.94-----1.1668--2021-08-20 15:00:00
2.94
####################
SELL
2021-08-20 15:00:00
1.16679
********************
-0.02-----1.1668--2021-08-20 15:00:00
-2.24-----1.16791--2021-08-20 16:00:00
-2.1-----1.16784--2021-08-20 17:00:00
-4.4-----1.16899--2021-08-20 18:00:00
-7.0-----1.17029--2021-08-20 19:00:00
-5.24-----1.16941--2021-08-20 20:00:00
-5.62-----1.1696--2021-08-20 21:00:00
-5.62-----1.1696--2021-08-20 21:00:00
####################
BUY
2021-08-20 21:00:00
1.16941
********************
checks
-0.38-----1.1696--2021-08-20 21:00:00
checks
-1.56-----1.17019--2021-08-20 22:00:00
checks
-0.54-----1.16968--2021-08-20 23:00:00
checks
0.18-----1.16932--2021-08-23 00:00:00
checks
0.24-----1.16929--2021-08-23 01:00:00
checks
-0.48-----1.16965--2021-08-23 02:00:00
checks
-0.98-----1.1699--2021-08-23 03:00:00
checks
-3.82-----1.17132--2021-08-23 04:00:00
checks
-4.64-----1.17173--2021-08-23 05:00:00
checks
-5.16-----1.17199--2021-08-23 06:00:00
checks
-4.88-----1.17185--2021-08-23 07:00:00
checks
-4.5-----1.17166--2021-08-23 08:00:00
checks
-3.82-----1.17132--2021-08-23 09:00:00
checks
-5.58-----1.1722--2021-08-23 10:00:00
checks
-7.32-----1.17307--2021-08-23 11:00:00
checks
-5.92-----1.17237--2021-08-23 12:00:00
checks
-6.72-----1.17277--2021-08-23 13:00:00
checks
-4.76-----1.17179--2021-08-23 14:00:00
checks
-7.54-----1.17318--2021-08-23 15:00:00
checks
-7.14-----1.17298--2021-08-23 16:00:00
checks
-9.08-----1.17395--2021-08-23 17:00:00
checks
-7.4-----1.17311--2021-08-23 18:00:00
checks
-8.96-----1.17389--2021-08-23 19:00:00
checks
-9.8-----1.17431--2021-08-23 20:00:00
checks
-10.74-----1.17478--2021-08-23 21:00:00
checks
-10.44-----1.17463--2021-08-23 22:00:00
checks
-9.3-----1.1740599999999999--2021-08-23 23:00:00
checks
-10.32-----1.1745700000000001--2021-08-24 00:00:00
checks
-10.22-----1.17452--2021-08-24 01:00:00
checks
-9.94-----1.17438--2021-08-24 02:00:00
checks
-8.98-----1.1739--2021-08-24 03:00:00
checks
-8.32-----1.17357--2021-08-24 04:00:00
checks
-9.5-----1.17416--2021-08-24 05:00:00
checks
-8.66-----1.17374--2021-08-24 06:00:00
checks
-9.32-----1.17407--2021-08-24 07:00:00
BREAK
BUY_price--->1.16941
-9.32-----1.17407--2021-08-24 08:00:00
-9.32
####################
SELL
2021-08-24 08:00:00
1.17408
********************
0.02-----1.17407--2021-08-24 08:00:00
0.32-----1.17392--2021-08-24 09:00:00
0.56-----1.1738--2021-08-24 10:00:00
2.52-----1.17282--2021-08-24 11:00:00
####################
SELL
2021-08-24 12:00:00

1.17281
********************
-0.48-----1.17305--2021-08-24 12:00:00
-1.44-----1.17353--2021-08-24 13:00:00
-1.54-----1.17358--2021-08-24 14:00:00
-4.42-----1.17502--2021-08-24 15:00:00
-3.9-----1.17476--2021-08-24 16:00:00
-6.48-----1.17605--2021-08-24 17:00:00
-3.62-----1.17462--2021-08-24 18:00:00
-3.62-----1.17462--2021-08-24 18:00:00
####################
BUY
2021-08-24 18:00:00
1.17605
********************
checks
2.86-----1.17462--2021-08-24 18:00:00
checks
2.7-----1.1747--2021-08-24 19:00:00
checks
3.16-----1.17447--2021-08-24 20:00:00
checks
1.26-----1.17542--2021-08-24 21:00:00
checks
0.68-----1.17571--2021-08-24 22:00:00
checks
1.04-----1.17553--2021-08-24 23:00:00
checks
1.1400000000000001-----1.17548--2021-08-25 00:00:00
checks
0.86-----1.1756199999999999--2021-08-25 01:00:00
checks
1.6400000000000001-----1.17523--2021-08-25 02:00:00
checks
3.86-----1.17412--2021-08-25 03:00:00
checks
4.98-----1.17356--2021-08-25 04:00:00
checks
4.6-----1.17375--2021-08-25 05:00:00
checks
4.5600000000000005-----1.17377--2021-08-25 06:00:00
BREAK
BUY_price--->1.17605
4.04-----1.17403--2021-08-25 07:00:00
4.04
####################
SELL
2021-08-25 07:00:00
1.17378
********************
-0.5-----1.17403--2021-08-25 07:00:00
-0.94-----1.17425--2021-08-25 08:00:00
1.04-----1.17326--2021-08-25 09:00:00
####################
SELL
2021-08-25 10:00:00
1.17327
********************
-0.92-----1.17373--2021-08-25 10:00:00
-3.64-----1.17509--2021-08-25 11:00:00
-3.2-----1.17487--2021-08-25 12:00:00
-2.84-----1.17469--2021-08-25 13:00:00
-1.56-----1.17405--2021-08-25 14:00:00
0.1-----1.17322--2021-08-25 15:00:00
-2.7800000000000002-----1.17466--2021-08-25 16:00:00
-3.26-----1.1749--2021-08-25 17:00:00
-4.7-----1.1756199999999999--2021-08-25 18:00:00
-4.7-----1.1756199999999999--2021-08-25 18:00:00
####################
BUY
2021-08-25 18:00:00
1.1749100000000001
********************
checks
-1.42-----1.1756199999999999--2021-08-25 18:00:00
checks
-2.14-----1.17598--2021-08-25 19:00:00
checks
-2.02-----1.17592--2021-08-25 20:00:00
checks
-4.36-----1.17709--2021-08-25 21:00:00
checks
-4.34-----1.17708--2021-08-25 22:00:00
checks
-3.86-----1.1768399999999999--2021-08-25 23:00:00
checks
-3.76-----1.17679--2021-08-26 00:00:00
checks
-4.28-----1.17705--2021-08-26 01:00:00
checks
-4.46-----1.17714--2021-08-26 02:00:00
checks
-3.5-----1.17666--2021-08-26 03:00:00
checks
-3.26-----1.17654--2021-08-26 04:00:00
checks
-3.04-----1.17643--2021-08-26 05:00:00
checks
-2.68-----1.17625--2021-08-26 06:00:00
checks
-2.92-----1.17637--2021-08-26 07:00:00
checks
-3.14-----1.17648--2021-08-26 08:00:00
checks
-1.58-----1.1757--2021-08-26 09:00:00
BREAK
BUY_price--->1.1749100000000001
-4.06-----1.17694--2021-08-26 10:00:00
-4.06
####################
SELL
2021-08-26 10:00:00
1.1757
********************
-2.48-----1.17694--2021-08-26 10:00:00
-0.32-----1.17586--2021-08-26 11:00:00
-2.5-----1.17695--2021-08-26 12:00:00
-3.52-----1.17746--2021-08-26 13:00:00
-2.44-----1.17692--2021-08-26 14:00:00
0.34-----1.17553--2021-08-26 15:00:00
0.72-----1.17534--2021-08-26 16:00:00
0.72-----1.17534--2021-08-26 17:00:00
-0.94-----1.17617--2021-08-26 18:00:00
0.98-----1.17521--2021-08-26 19:00:00
0.76-----1.17532--2021-08-26 20:00:00
1.1-----1.17515--2021-08-26 21:00:00
####################
SELL
2021-08-26 22:00:00
1.17516
********************
-0.58-----1.17545--2021-08-26 22:00:00
0.7-----1.17481--2021-08-26 23:00:00
-0.62-----1.17547--2021-08-27 00:00:00
-0.88-----1.1756--2021-08-27 01:00:00
-0.3-----1.17531--2021-08-27 02:00:00
1.34-----1.17449--2021-08-27 03:00:00
####################
SELL
2021-08-27 04:00:00
1.17448
********************
-0.88-----1.17492--2021-08-27 04:00:00
-1.5-----1.17523--2021-08-27 05:00:00
-2.9-----1.17593--2021-08-27 06:00:00
-3.62-----1.17629--2021-08-27 07:00:00
-3.22-----1.17609--2021-08-27 08:00:00
-4.5600000000000005-----1.17676--2021-08-27 09:00:00
-3.2-----1.17608--2021-08-27 10:00:00
-3.2-----1.17608--2021-08-27 10:00:00
####################
BUY
2021-08-27 10:00:00
1.17679
********************
checks
1.42-----1.17608--2021-08-27 10:00:00
checks
3.46-----1.17506--2021-08-27 11:00:00
checks
2.02-----1.17578--2021-08-27 12:00:00
checks
1.88-----1.17585--2021-08-27 13:00:00
checks
1.16-----1.17621--2021-08-27 14:00:00
checks
2.44-----1.17557--2021-08-27 15:00:00
checks
0.78-----1.1764000000000001--2021-08-27 16:00:00
checks
-3.64-----1.17861--2021-08-27 17:00:00
checks
-5.0-----1.17929--2021-08-27 18:00:00
checks
-6.48-----1.18003--2021-08-27 19:00:00
checks
-5.34-----1.17946--2021-08-27 20:00:00
checks
-5.22-----1.1794--2021-08-27 21:00:00
checks
-5.66-----1.17962--2021-08-27 22:00:00
checks
-4.9399999999999995-----1.17926--2021-08-27 23:00:00

In [26]:
n = 0
p = 0
tn = 0
tp = 0

for i in profit:
    if i<0.0:
        n = n+i
        tn = tn+1
    else:
        p = p+i
        tp = tp+1
print(sum(profit))

print(f"Total negative sm -->{n}")
print(f"Total negative -->{tn}")      
print(f"Total positive sm -->{p}")      
print(f"Total positive -->{tp}") 
print(f"Length {len(profit)}")

171.01999999999995
Total negative sm -->-65.62
Total negative -->20
Total positive sm -->236.6399999999999
Total positive -->96
Length 116

In [24]:
for i in profit:
    pri

1.12

In [ ]:
# plt.plot(a[-10:].smaC)
# plt.plot(a[-10:].smaO)
a['smaC'][-90:].plot(figsize=(15,6))
# rates_frame['ll'] = rates_frame['close'].rolling(window=100).mean()
a['smaO'][-90:].plot()
b['close'][-90:].plot()

# plt.plot( l[200:-100], 'r').rolling(window=100).

plt.xticks(rotation = 45)

In [ ]:
  elif check == 1:
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")


        if pp > 0.0:
            check = 0
            profit.append(pp)
            index.append(pp)
            print("Greater")
        elif a.iloc[i].smaC < a.iloc[i].smaO:
            check = 0
            profit.append(pp)
            if pp > 0.0:
                index.append(pp)
            else:
                indexB.append(pp)
            print("smaC<smaO")
        elif a.iloc[i].smaC > a.iloc[i].smaO:
            check = 0
            profit.append(pp)
            if pp > 0.0:
                index.append(pp)
            else:
                indexB.append(pp)
            print("smaC>smaO")
#         i = i-2
#         print(i)

In [ ]:
#less negatives more positives
# symbol = "CADJPY"
# b= get_values1(symbol)
# b = b.dropna()
b = a
B = []
check = 0
profit = []
index = []
indexB = []
counter = 0
peck = 0
p= []
checks = 0
counterr = 0
profits = []
up = 0
rsi1 = []
rsi2 = []
mul = 100000
global_loss = []
conti = []

for i in range(2,len(a)-1):
    if a.iloc[i-1].smaC < a.iloc[i-1].smaO and check == 0:
        buy_price = b.iloc[i].open #BUY Action
        p2 = threading.Thread(target=follow, args=(i, a, buy_price, mt5.ORDER_TYPE_SELL))
        p2.start()
        print("#"*20)
        print("SELL")
        print(round(a.iloc[i-2].smaC, 6), round(a.iloc[i-2].smaO, 6), a.iloc[i-2].name)
        print(round(a.iloc[i-1].smaC, 6), round(a.iloc[i-1].smaO, 6), a.iloc[i-1].name)
        if (round(a.iloc[i-1].smaC, 6) - round(a.iloc[i-1].smaO, 6)) <  :
        
        print(round(a.iloc[i+1].smaC, 6), round(a.iloc[i+1].smaO, 6), a.iloc[i+1].name)
        
        
        
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        check = 1
        checks = 0
    elif a.iloc[i-1].smaC > a.iloc[i-1].smaO and checks == 0:
        buy_price = b.iloc[i].open #BUY Action
        p3 = threading.Thread(target=follow, args=(i, a, buy_price,mt5.ORDER_TYPE_BUY))
        p3.start()
        print("#"*20)
        print("BUY")
        print(round(a.iloc[i-1].smaC, 6), round(a.iloc[i-1].smaO, 6), a.iloc[i-1].name)
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        checks = 1
        check = 0