In [1]:
from datetime import datetime
import MetaTrader5 as mt5
import pandas as pd
import pytz
import time
import pandas_ta as pta
import matplotlib.pyplot as plt 
import threading

# import threading
mt5.initialize()

True

In [2]:
def price_action(symbol, lot, ask, bid, order_type):
    buy_profit=mt5.order_calc_profit(order_type,symbol,lot,ask,bid)
    return buy_profit
price_action("EURUSD", 0.02, 1.18969, 1.17030,mt5.ORDER_TYPE_SELL)

38.78

In [33]:
def get_values(symbol):
    timezone = pytz.timezone("Etc/UTC")
    x = datetime.now()
    utc_from = datetime(x.year, x.month, 1, tzinfo=timezone)
    utc_to = datetime(x.year, x.month, x.day+1, tzinfo=timezone)
    rates = mt5.copy_rates_range(symbol, mt5.TIMEFRAME_H1, utc_from, utc_to)

    rates_frame = pd.DataFrame(rates)
#     rates_frame = rates_frame.iloc[-150:]
    rates_frame = rates_frame.drop(['tick_volume', 'spread', 'real_volume'], axis=1)
    # convert time in seconds into the datetime format
    rates_frame['clsma']= rates_frame['close'].rolling(window=8).mean()
    rates_frame['smaC']= rates_frame['clsma'].rolling(window=8).mean()


    rates_frame['clsma']= rates_frame['open'].rolling(window=8).mean()
    rates_frame['smaO']= rates_frame['clsma'].rolling(window=8).mean()

    rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')
    rates_frame = rates_frame.set_index('time')
    rates_frame = rates_frame.drop(['high', 'low', 'clsma'], axis=1)
    return rates_frame

In [34]:
global global_loss
global profit
global conti


profit = []

global_loss = []
symbol = "EURGBP"
b = get_values(symbol)
b = b.dropna()
b

                        open    close      smaC      smaO
time
2021-08-02 14:00:00  0.85538  0.85530  0.853917  0.853842
2021-08-02 15:00:00  0.85530  0.85471  0.853977  0.853919
2021-08-02 16:00:00  0.85471  0.85407  0.854046  0.853978
2021-08-02 17:00:00  0.85414  0.85460  0.854124  0.854048
2021-08-02 18:00:00  0.85462  0.85503  0.854227  0.854127
...                      ...      ...       ...       ...
2021-08-24 18:00:00  0.85634  0.85640  0.855484  0.855411
2021-08-24 19:00:00  0.85640  0.85603  0.855571  0.855485
2021-08-24 20:00:00  0.85605  0.85561  0.855660  0.855572
2021-08-24 21:00:00  0.85562  0.85602  0.855765  0.855661
2021-08-24 22:00:00  0.85602  0.85610  0.855888  0.855766

[393 rows x 4 columns]

In [32]:
global global_loss
global profit
global conti


profit = []

global_loss = []
symbol = "EURGBP"
a= get_values(symbol)
a = a.dropna()
a

                        open    close      smaC      smaO
time
2021-08-24 17:00:00  0.85620  0.85635  0.855410  0.855348
2021-08-24 18:00:00  0.85634  0.85640  0.855484  0.855411
2021-08-24 19:00:00  0.85640  0.85603  0.855571  0.855485
2021-08-24 20:00:00  0.85605  0.85561  0.855660  0.855572
2021-08-24 21:00:00  0.85562  0.85602  0.855765  0.855661
2021-08-24 22:00:00  0.85602  0.85606  0.855887  0.855766

In [ ]:
def follow(j, a, buy_price, order_type):
    loss = 0.0
    g = 0
    for k in range(j+1, len(a)):
        sell_price = a.iloc[k].close
        pp = price_action(symbol, 0.02, buy_price, sell_price, order_type)
        if pp > 1.0:
            profit.append(pp)
            global_loss.append(loss)
            break
        elif pp < 0.0:
            if pp < loss:
                loss = pp
    if k == len(a)-1:
        conti.append([pp, a.iloc[j-1].name])

In [26]:
#less negatives more positives
# symbol = "CADJPY"
# b= get_values1(symbol)
# b = b.dropna()
b = a
B = []
check = 0
profit = []
index = []
indexB = []
counter = 0
peck = 0
p= []
checks = 0
counterr = 0
profits = []
up = 0
rsi1 = []
rsi2 = []
mul = 100000
global_loss = []
conti = []

for i in range(2,len(a)):
    if a.iloc[i-1].smaC < a.iloc[i-1].smaO and check == 0:
        if checks == 1:
            print("BREAK")
            sell_price = a.iloc[i].close
            pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
            print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
            checks = 0
            profit.append(pp)
        buy_price = a.iloc[i].open #SELL Action
        print("#"*20)
        print("SELL")
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        check = 1
        checks = 0
    if check == 1:
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
        if pp > 1.0:
            check = 0
            profit.append(pp)
    if a.iloc[i-1].smaC > a.iloc[i-1].smaO and checks == 0:
        if check == 1:
            sell_price = a.iloc[i].close
            pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
            print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
            check = 0
            profit.append(pp)
        buy_price = a.iloc[i].open #BUY Action
        print("#"*20)
        print("BUY")
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        checks = 1
        check = 0
    if checks == 1:
        print("checks")
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")
        if pp > 1.0:
            check = 0
            profit.append(pp)

####################
BUY
2021-08-02 16:00:00
0.85471
********************
checks
1.76-----0.85407--2021-08-02 16:00:00
checks
0.3-----0.8546--2021-08-02 17:00:00
checks
-0.88-----0.85503--2021-08-02 18:00:00
checks
1.5899999999999999-----0.85413--2021-08-02 19:00:00
checks
0.69-----0.85446--2021-08-02 20:00:00
checks
0.47-----0.85454--2021-08-02 21:00:00
checks
0.71-----0.85445--2021-08-02 22:00:00
checks
1.51-----0.85416--2021-08-02 23:00:00
checks
0.25-----0.85462--2021-08-03 00:00:00
BREAK
-0.03-----0.85472--2021-08-03 01:00:00
####################
SELL
2021-08-03 01:00:00
0.8547
********************
-0.05-----0.85472--2021-08-03 01:00:00
-0.03-----0.85471--2021-08-03 02:00:00
1.02-----0.85433--2021-08-03 03:00:00
####################
SELL
2021-08-03 04:00:00
0.85433
********************
-0.11-----0.85437--2021-08-03 04:00:00
-0.25-----0.85442--2021-08-03 05:00:00
-0.8-----0.85462--2021-08-03 06:00:00
-1.51-----0.85488--2021-08-03 07:00:00
-0.91-----0.85466--2021-08-03 08:00:00
0.36-----0.8542--2021-08-03 09:00:00
1.8900000000000001-----0.85364--2021-08-03 10:00:00
####################
SELL
2021-08-03 11:00:00
0.85364
********************
-1.13-----0.85405--2021-08-03 11:00:00
-1.02-----0.85401--2021-08-03 12:00:00
1.87-----0.85296--2021-08-03 13:00:00
####################
SELL
2021-08-03 14:00:00
0.85296
********************
-1.43-----0.85348--2021-08-03 14:00:00
-1.98-----0.85368--2021-08-03 15:00:00
-4.53-----0.85461--2021-08-03 16:00:00
-1.62-----0.85355--2021-08-03 17:00:00
0.55-----0.85276--2021-08-03 18:00:00
0.74-----0.85269--2021-08-03 19:00:00
0.3-----0.85285--2021-08-03 20:00:00
1.51-----0.85241--2021-08-03 21:00:00
####################
SELL
2021-08-03 22:00:00
0.85243
********************
0.05-----0.85241--2021-08-03 22:00:00
0.22-----0.85235--2021-08-03 23:00:00
0.11-----0.85239--2021-08-04 00:00:00
-0.96-----0.85278--2021-08-04 01:00:00
-0.91-----0.85276--2021-08-04 02:00:00
-1.78-----0.85308--2021-08-04 03:00:00
-0.05-----0.85245--2021-08-04 04:00:00
0.0-----0.85243--2021-08-04 05:00:00
-0.38-----0.85257--2021-08-04 06:00:00
0.27-----0.85233--2021-08-04 07:00:00
0.11-----0.85239--2021-08-04 08:00:00
1.46-----0.8519--2021-08-04 09:00:00
####################
SELL
2021-08-04 10:00:00
0.8519
********************
0.41-----0.85175--2021-08-04 10:00:00
3.84-----0.8505--2021-08-04 11:00:00
####################
SELL
2021-08-04 12:00:00
0.8505
********************
-0.88-----0.85082--2021-08-04 12:00:00
-2.22-----0.85131--2021-08-04 13:00:00
-3.32-----0.85171--2021-08-04 14:00:00
-6.48-----0.85286--2021-08-04 15:00:00
-5.41-----0.85247--2021-08-04 16:00:00
-2.5-----0.85141--2021-08-04 17:00:00
-1.76-----0.85114--2021-08-04 18:00:00
-3.3-----0.8517--2021-08-04 19:00:00
-2.86-----0.85154--2021-08-04 20:00:00
-4.9399999999999995-----0.8523--2021-08-04 21:00:00
-5.05-----0.85234--2021-08-04 22:00:00
-5.05-----0.85234--2021-08-04 22:00:00
####################
BUY
2021-08-04 22:00:00
0.85232
********************
checks
-0.05-----0.85234--2021-08-04 22:00:00
checks
2.36-----0.85146--2021-08-04 23:00:00
checks
0.93-----0.85198--2021-08-05 00:00:00
checks
0.0-----0.85232--2021-08-05 01:00:00
checks
0.47-----0.85215--2021-08-05 02:00:00
checks
1.1-----0.85192--2021-08-05 03:00:00
checks
0.8-----0.85203--2021-08-05 04:00:00
checks
-0.14-----0.85237--2021-08-05 05:00:00
BREAK
1.32-----0.85184--2021-08-05 06:00:00
####################
SELL
2021-08-05 06:00:00
0.85237
********************
1.46-----0.85184--2021-08-05 06:00:00
####################
SELL
2021-08-05 07:00:00
0.85184
********************
-0.49-----0.85202--2021-08-05 07:00:00
0.22-----0.85176--2021-08-05 08:00:00
0.49-----0.85166--2021-08-05 09:00:00
2.64-----0.85088--2021-08-05 10:00:00
####################
SELL
2021-08-05 11:00:00
0.85089
********************
0.91-----0.85056--2021-08-05 11:00:00
2.2800000000000002-----0.85006--2021-08-05 12:00:00
####################
SELL
2021-08-05 13:00:00
0.85005
********************
-1.51-----0.8506--2021-08-05 13:00:00
-3.27-----0.85124--2021-08-05 14:00:00
-2.86-----0.85109--2021-08-05 15:00:00
-2.33-----0.8509--2021-08-05 16:00:00
1.13-----0.84964--2021-08-05 17:00:00
####################
SELL
2021-08-05 18:00:00
0.84964
********************
-0.49-----0.84982--2021-08-05 18:00:00
-0.25-----0.84973--2021-08-05 19:00:00
1.18-----0.84921--2021-08-05 20:00:00
####################
SELL
2021-08-05 21:00:00
0.84921
********************
-0.63-----0.84944--2021-08-05 21:00:00
-0.8-----0.8495--2021-08-05 22:00:00
0.22-----0.84913--2021-08-05 23:00:00
0.25-----0.84912--2021-08-06 00:00:00
-0.44-----0.84937--2021-08-06 01:00:00
-0.91-----0.84954--2021-08-06 02:00:00
-0.88-----0.84953--2021-08-06 03:00:00
-0.96-----0.84956--2021-08-06 04:00:00
0.11-----0.84917--2021-08-06 05:00:00
0.03-----0.8492--2021-08-06 06:00:00
-0.49-----0.84939--2021-08-06 07:00:00
-0.33-----0.84933--2021-08-06 08:00:00
0.25-----0.84912--2021-08-06 09:00:00
-0.08-----0.84924--2021-08-06 10:00:00
1.81-----0.84855--2021-08-06 11:00:00
####################
SELL
2021-08-06 12:00:00
0.84854
********************
-0.91-----0.84887--2021-08-06 12:00:00
-0.3-----0.84865--2021-08-06 13:00:00
0.66-----0.8483--2021-08-06 14:00:00
2.69-----0.84756--2021-08-06 15:00:00
####################
SELL
2021-08-06 16:00:00
0.84756
********************
-0.41-----0.84771--2021-08-06 16:00:00
-1.21-----0.848--2021-08-06 17:00:00
-0.44-----0.84772--2021-08-06 18:00:00
-0.58-----0.84777--2021-08-06 19:00:00
0.14-----0.84751--2021-08-06 20:00:00
0.55-----0.84736--2021-08-06 21:00:00
0.77-----0.84728--2021-08-06 22:00:00
0.77-----0.84728--2021-08-06 23:00:00
2.33-----0.84671--2021-08-09 00:00:00
####################
SELL
2021-08-09 01:00:00
0.84679
********************
-1.8900000000000001-----0.84748--2021-08-09 01:00:00
-0.74-----0.84706--2021-08-09 02:00:00
-2.42-----0.84767--2021-08-09 03:00:00
-3.65-----0.84812--2021-08-09 04:00:00
-3.57-----0.84809--2021-08-09 05:00:00
-2.88-----0.84784--2021-08-09 06:00:00
-3.4-----0.84803--2021-08-09 07:00:00
-2.83-----0.84782--2021-08-09 08:00:00
-0.82-----0.84709--2021-08-09 09:00:00
-0.82-----0.84709--2021-08-09 09:00:00
####################
BUY
2021-08-09 09:00:00
0.8478
********************
checks
1.95-----0.84709--2021-08-09 09:00:00
checks
-0.25-----0.84789--2021-08-09 10:00:00
checks
-1.07-----0.84819--2021-08-09 11:00:00
checks
3.4-----0.84656--2021-08-09 12:00:00
checks
2.88-----0.84675--2021-08-09 13:00:00
checks
0.33-----0.84768--2021-08-09 14:00:00
BREAK
2.14-----0.84702--2021-08-09 15:00:00
####################
SELL
2021-08-09 15:00:00
0.84768
********************
1.81-----0.84702--2021-08-09 15:00:00
####################
SELL
2021-08-09 16:00:00
0.84703
********************
-2.64-----0.84799--2021-08-09 16:00:00
-2.69-----0.84801--2021-08-09 17:00:00
-2.9699999999999998-----0.84811--2021-08-09 18:00:00
-2.39-----0.8479--2021-08-09 19:00:00
-2.0-----0.84776--2021-08-09 20:00:00
-1.04-----0.84741--2021-08-09 21:00:00
-1.13-----0.84744--2021-08-09 22:00:00
-1.13-----0.84744--2021-08-09 22:00:00
####################
BUY
2021-08-09 22:00:00
0.84741
********************
checks
-0.08-----0.84744--2021-08-09 22:00:00
checks
1.76-----0.84677--2021-08-09 23:00:00
checks
1.81-----0.84675--2021-08-10 00:00:00
checks
-0.22-----0.84749--2021-08-10 01:00:00
BREAK
-0.22-----0.84749--2021-08-10 02:00:00
####################
SELL
2021-08-10 02:00:00
0.84749
********************
0.0-----0.84749--2021-08-10 02:00:00
0.47-----0.84732--2021-08-10 03:00:00
-0.6-----0.84771--2021-08-10 04:00:00
-1.13-----0.8479--2021-08-10 05:00:00
-0.44-----0.84765--2021-08-10 06:00:00
-0.71-----0.84775--2021-08-10 07:00:00
-0.25-----0.84758--2021-08-10 08:00:00
0.19-----0.84742--2021-08-10 09:00:00
1.8900000000000001-----0.8468--2021-08-10 10:00:00
####################
SELL
2021-08-10 11:00:00
0.84681
********************
2.0-----0.84608--2021-08-10 11:00:00
####################
SELL
2021-08-10 12:00:00
0.84605
********************
0.8-----0.84576--2021-08-10 12:00:00
0.3-----0.84594--2021-08-10 13:00:00
1.29-----0.84558--2021-08-10 14:00:00
####################
SELL
2021-08-10 15:00:00
0.84557
********************
-0.36-----0.8457--2021-08-10 15:00:00
-1.81-----0.84623--2021-08-10 16:00:00
-1.76-----0.84621--2021-08-10 17:00:00
-3.62-----0.84689--2021-08-10 18:00:00
-3.6-----0.84688--2021-08-10 19:00:00
-3.19-----0.84673--2021-08-10 20:00:00
-3.73-----0.84693--2021-08-10 21:00:00
-3.79-----0.84695--2021-08-10 22:00:00
-3.05-----0.84668--2021-08-10 23:00:00
-1.67-----0.84618--2021-08-11 00:00:00
-1.67-----0.84618--2021-08-11 00:00:00
####################
BUY
2021-08-11 00:00:00
0.84623
********************
checks
0.14-----0.84618--2021-08-11 00:00:00
checks
-2.09-----0.84699--2021-08-11 01:00:00
checks
-2.09-----0.84699--2021-08-11 02:00:00
checks
-2.8-----0.84725--2021-08-11 03:00:00
checks
-3.6-----0.84754--2021-08-11 04:00:00
checks
-3.62-----0.84755--2021-08-11 05:00:00
checks
-3.1-----0.84736--2021-08-11 06:00:00
checks
-2.88-----0.84728--2021-08-11 07:00:00
checks
-2.8-----0.84725--2021-08-11 08:00:00
checks
-1.73-----0.84686--2021-08-11 09:00:00
checks
-3.95-----0.84767--2021-08-11 10:00:00
checks
-5.13-----0.8481--2021-08-11 11:00:00
checks
-3.9-----0.84765--2021-08-11 12:00:00
checks
-4.12-----0.84773--2021-08-11 13:00:00
checks
-2.31-----0.84707--2021-08-11 14:00:00
checks
-1.26-----0.84669--2021-08-11 15:00:00
checks
-1.67-----0.84684--2021-08-11 16:00:00
checks
-0.63-----0.84646--2021-08-11 17:00:00
checks
-0.52-----0.84642--2021-08-11 18:00:00
BREAK
-0.38-----0.84637--2021-08-11 19:00:00
####################
SELL
2021-08-11 19:00:00
0.84642
********************
0.14-----0.84637--2021-08-11 19:00:00
-0.08-----0.84645--2021-08-11 20:00:00
-0.41-----0.84657--2021-08-11 21:00:00
-0.08-----0.84645--2021-08-11 22:00:00
1.65-----0.84582--2021-08-11 23:00:00
####################
SELL
2021-08-12 00:00:00
0.84585
********************
-0.58-----0.84606--2021-08-12 00:00:00
-1.81-----0.84651--2021-08-12 01:00:00
-2.42-----0.84673--2021-08-12 02:00:00
-1.24-----0.8463--2021-08-12 03:00:00
-1.26-----0.84631--2021-08-12 04:00:00
-1.24-----0.8463--2021-08-12 05:00:00
-1.46-----0.84638--2021-08-12 06:00:00
-1.54-----0.84641--2021-08-12 07:00:00
-1.43-----0.84637--2021-08-12 08:00:00
-2.39-----0.84672--2021-08-12 09:00:00
-0.41-----0.846--2021-08-12 10:00:00
-0.41-----0.846--2021-08-12 10:00:00
####################
BUY
2021-08-12 10:00:00
0.84672
********************
checks
1.98-----0.846--2021-08-12 10:00:00
BREAK
-1.54-----0.84728--2021-08-12 11:00:00
####################
SELL
2021-08-12 11:00:00
0.846
********************
-3.51-----0.84728--2021-08-12 11:00:00
-2.22-----0.84681--2021-08-12 12:00:00
-2.22-----0.84681--2021-08-12 12:00:00
####################
BUY
2021-08-12 12:00:00
0.84733
********************
checks
1.43-----0.84681--2021-08-12 12:00:00
checks
0.33-----0.84721--2021-08-12 13:00:00
checks
-0.77-----0.84761--2021-08-12 14:00:00
checks
-1.15-----0.84775--2021-08-12 15:00:00
checks
-0.49-----0.84751--2021-08-12 16:00:00
checks
-1.29-----0.8478--2021-08-12 17:00:00
checks
-2.69-----0.84831--2021-08-12 18:00:00
checks
-5.93-----0.84949--2021-08-12 19:00:00
checks
-6.37-----0.84965--2021-08-12 20:00:00
checks
-7.19-----0.84995--2021-08-12 21:00:00
checks
-7.14-----0.84993--2021-08-12 22:00:00
checks
-4.31-----0.8489--2021-08-12 23:00:00
checks
-4.78-----0.84907--2021-08-13 00:00:00
checks
-6.29-----0.84962--2021-08-13 01:00:00
checks
-6.43-----0.84967--2021-08-13 02:00:00
checks
-6.54-----0.84971--2021-08-13 03:00:00
checks
-7.25-----0.84997--2021-08-13 04:00:00
checks
-7.0-----0.84988--2021-08-13 05:00:00
checks
-6.67-----0.84976--2021-08-13 06:00:00
checks
-6.51-----0.8497--2021-08-13 07:00:00
checks
-6.78-----0.8498--2021-08-13 08:00:00
checks
-6.97-----0.84987--2021-08-13 09:00:00
checks
-6.62-----0.84974--2021-08-13 10:00:00
checks
-9.64-----0.85084--2021-08-13 11:00:00
checks
-10.3-----0.85108--2021-08-13 12:00:00
checks
-11.01-----0.85134--2021-08-13 13:00:00
checks
-9.78-----0.85089--2021-08-13 14:00:00
checks
-9.23-----0.85069--2021-08-13 15:00:00
checks
-7.61-----0.8501--2021-08-13 16:00:00
checks
-10.52-----0.85116--2021-08-13 17:00:00
checks
-10.6-----0.85119--2021-08-13 18:00:00
checks
-9.78-----0.85089--2021-08-13 19:00:00
checks
-8.21-----0.85032--2021-08-13 20:00:00
checks
-8.51-----0.85043--2021-08-13 21:00:00
checks
-8.7-----0.8505--2021-08-13 22:00:00
checks
-7.77-----0.85016--2021-08-13 23:00:00
checks
-6.92-----0.84985--2021-08-16 00:00:00
checks
-8.32-----0.85036--2021-08-16 01:00:00
BREAK
-8.95-----0.85059--2021-08-16 02:00:00
####################
SELL
2021-08-16 02:00:00
0.85034
********************
-0.69-----0.85059--2021-08-16 02:00:00

-2.03-----0.85108--2021-08-16 03:00:00
-1.5699999999999998-----0.85091--2021-08-16 04:00:00
-1.13-----0.85075--2021-08-16 05:00:00
-1.13-----0.85075--2021-08-16 05:00:00
####################
BUY
2021-08-16 05:00:00
0.85091
********************
checks
0.44-----0.85075--2021-08-16 05:00:00
checks
-0.25-----0.851--2021-08-16 06:00:00
checks
-0.47-----0.85108--2021-08-16 07:00:00
checks
-0.66-----0.85115--2021-08-16 08:00:00
checks
-0.71-----0.85117--2021-08-16 09:00:00
checks
1.95-----0.8502--2021-08-16 10:00:00
checks
1.65-----0.85031--2021-08-16 11:00:00
checks
2.0-----0.85018--2021-08-16 12:00:00
checks
2.8-----0.84989--2021-08-16 13:00:00
checks
6.21-----0.84865--2021-08-16 14:00:00
BREAK
4.26-----0.84936--2021-08-16 15:00:00
####################
SELL
2021-08-16 15:00:00
0.84866
********************
-1.92-----0.84936--2021-08-16 15:00:00
-6.95-----0.85119--2021-08-16 16:00:00
-4.97-----0.85047--2021-08-16 17:00:00
-4.39-----0.85026--2021-08-16 18:00:00
-4.7-----0.85037--2021-08-16 19:00:00
-5.38-----0.85062--2021-08-16 20:00:00
-6.18-----0.85091--2021-08-16 21:00:00
-6.37-----0.85098--2021-08-16 22:00:00
-4.34-----0.85024--2021-08-16 23:00:00
-4.34-----0.85024--2021-08-16 23:00:00
####################
BUY
2021-08-16 23:00:00
0.85099
********************
checks
2.06-----0.85024--2021-08-16 23:00:00
checks
1.4-----0.85048--2021-08-17 00:00:00
checks
0.44-----0.85083--2021-08-17 01:00:00
checks
0.41-----0.85084--2021-08-17 02:00:00
checks
0.27-----0.85089--2021-08-17 03:00:00
checks
-0.82-----0.85129--2021-08-17 04:00:00
checks
-1.4-----0.8515--2021-08-17 05:00:00
checks
-1.98-----0.85171--2021-08-17 06:00:00
checks
-1.46-----0.85152--2021-08-17 07:00:00
checks
-0.77-----0.85127--2021-08-17 08:00:00
checks
-3.27-----0.85218--2021-08-17 09:00:00
checks
-5.38-----0.85295--2021-08-17 10:00:00
checks
-4.61-----0.85267--2021-08-17 11:00:00
checks
-5.13-----0.85286--2021-08-17 12:00:00
checks
-5.57-----0.85302--2021-08-17 13:00:00
checks
-5.44-----0.85297--2021-08-17 14:00:00
checks
-4.26-----0.85254--2021-08-17 15:00:00
checks
-6.01-----0.85318--2021-08-17 16:00:00
checks
-5.0-----0.85281--2021-08-17 17:00:00
checks
-4.17-----0.85251--2021-08-17 18:00:00
checks
-5.24-----0.8529--2021-08-17 19:00:00
checks
-5.55-----0.85301--2021-08-17 20:00:00
checks
-4.06-----0.85247--2021-08-17 21:00:00
checks
-3.87-----0.8524--2021-08-17 22:00:00
checks
-1.65-----0.85159--2021-08-17 23:00:00
checks
-2.39-----0.85186--2021-08-18 00:00:00
BREAK
-2.5300000000000002-----0.85191--2021-08-18 01:00:00
####################
SELL
2021-08-18 01:00:00
0.85195
********************
0.11-----0.85191--2021-08-18 01:00:00
-0.38-----0.85209--2021-08-18 02:00:00
-0.8-----0.85224--2021-08-18 03:00:00
0.08-----0.85192--2021-08-18 04:00:00
-0.08-----0.85198--2021-08-18 05:00:00
0.3-----0.85184--2021-08-18 06:00:00
-1.8399999999999999-----0.85262--2021-08-18 07:00:00
-1.02-----0.85232--2021-08-18 08:00:00
-1.29-----0.85242--2021-08-18 09:00:00
-3.02-----0.85305--2021-08-18 10:00:00
0.38-----0.85181--2021-08-18 11:00:00
-0.44-----0.85211--2021-08-18 12:00:00
1.07-----0.85156--2021-08-18 13:00:00
####################
BUY
2021-08-18 13:00:00
0.85212
********************
checks
1.54-----0.85156--2021-08-18 13:00:00
checks
2.36-----0.85126--2021-08-18 14:00:00
checks
2.8-----0.8511--2021-08-18 15:00:00
BREAK
3.4-----0.85088--2021-08-18 16:00:00
####################
SELL
2021-08-18 16:00:00
0.8511
********************
0.6-----0.85088--2021-08-18 16:00:00
-0.44-----0.85126--2021-08-18 17:00:00
-0.03-----0.85111--2021-08-18 18:00:00
0.66-----0.85086--2021-08-18 19:00:00
0.63-----0.85087--2021-08-18 20:00:00
0.33-----0.85098--2021-08-18 21:00:00
-0.49-----0.85128--2021-08-18 22:00:00
1.8399999999999999-----0.85043--2021-08-18 23:00:00
####################
SELL
2021-08-19 00:00:00
0.85077
********************
0.03-----0.85076--2021-08-19 00:00:00
-1.67-----0.85138--2021-08-19 01:00:00
-1.95-----0.85148--2021-08-19 02:00:00
-0.38-----0.85091--2021-08-19 03:00:00
-0.99-----0.85113--2021-08-19 04:00:00
-0.66-----0.85101--2021-08-19 05:00:00
-0.3-----0.85088--2021-08-19 06:00:00
-0.49-----0.85095--2021-08-19 07:00:00
-1.02-----0.85114--2021-08-19 08:00:00
-2.8-----0.85179--2021-08-19 09:00:00
-5.68-----0.85284--2021-08-19 10:00:00
-10.05-----0.85443--2021-08-19 11:00:00
-10.05-----0.85443--2021-08-19 11:00:00
####################
BUY
2021-08-19 11:00:00
0.85289
********************
checks
-4.23-----0.85443--2021-08-19 11:00:00
checks
-3.43-----0.85414--2021-08-19 12:00:00
checks
-3.71-----0.85424--2021-08-19 13:00:00
checks
-5.85-----0.85502--2021-08-19 14:00:00
checks
-5.88-----0.85503--2021-08-19 15:00:00
checks
-4.39-----0.85449--2021-08-19 16:00:00
checks
-6.12-----0.85512--2021-08-19 17:00:00
checks
-6.37-----0.85521--2021-08-19 18:00:00
checks
-8.57-----0.85601--2021-08-19 19:00:00
checks
-7.5-----0.85562--2021-08-19 20:00:00
checks
-8.68-----0.85605--2021-08-19 21:00:00
checks
-9.47-----0.85634--2021-08-19 22:00:00
checks
-6.59-----0.85529--2021-08-19 23:00:00
checks
-8.27-----0.8559--2021-08-20 00:00:00
checks
-9.67-----0.85641--2021-08-20 01:00:00
checks
-10.13-----0.85658--2021-08-20 02:00:00
checks
-9.53-----0.85636--2021-08-20 03:00:00
checks
-11.72-----0.85716--2021-08-20 04:00:00
checks
-12.05-----0.85728--2021-08-20 05:00:00
checks
-11.92-----0.85723--2021-08-20 06:00:00
checks
-11.48-----0.85707--2021-08-20 07:00:00
checks
-11.56-----0.8571--2021-08-20 08:00:00
checks
-13.4-----0.85777--2021-08-20 09:00:00
checks
-12.88-----0.85758--2021-08-20 10:00:00
checks
-11.04-----0.85691--2021-08-20 11:00:00
checks
-12.05-----0.85728--2021-08-20 12:00:00
checks
-12.66-----0.8575--2021-08-20 13:00:00
checks
-11.75-----0.85717--2021-08-20 14:00:00
checks
-12.77-----0.85754--2021-08-20 15:00:00
checks
-10.79-----0.85682--2021-08-20 16:00:00
checks
-13.4-----0.85777--2021-08-20 17:00:00
checks
-13.67-----0.85787--2021-08-20 18:00:00
checks
-15.87-----0.85867--2021-08-20 19:00:00
checks
-15.29-----0.85846--2021-08-20 20:00:00
checks
-15.49-----0.85853--2021-08-20 21:00:00
checks
-16.15-----0.85877--2021-08-20 22:00:00
checks
-14.8-----0.85828--2021-08-20 23:00:00
checks
-13.65-----0.85786--2021-08-23 00:00:00
checks
-14.72-----0.85825--2021-08-23 01:00:00
checks
-15.21-----0.85843--2021-08-23 02:00:00
checks
-12.82-----0.85756--2021-08-23 03:00:00
checks
-14.31-----0.8581--2021-08-23 04:00:00
checks
-15.98-----0.85871--2021-08-23 05:00:00
checks
-15.76-----0.85863--2021-08-23 06:00:00
checks
-15.43-----0.85851--2021-08-23 07:00:00
checks
-14.11-----0.85803--2021-08-23 08:00:00
checks
-13.78-----0.85791--2021-08-23 09:00:00
checks
-15.87-----0.85867--2021-08-23 10:00:00
checks
-17.02-----0.85909--2021-08-23 11:00:00
checks
-13.13-----0.85767--2021-08-23 12:00:00
checks
-12.41-----0.85741--2021-08-23 13:00:00
checks
-9.56-----0.85637--2021-08-23 14:00:00
BREAK
-9.91-----0.8565--2021-08-23 15:00:00
####################
SELL
2021-08-23 15:00:00
0.85636
********************
-0.38-----0.8565--2021-08-23 15:00:00
0.08-----0.85633--2021-08-23 16:00:00
1.76-----0.85572--2021-08-23 17:00:00
####################
SELL
2021-08-23 18:00:00
0.8557
********************
1.21-----0.85526--2021-08-23 18:00:00
####################
SELL
2021-08-23 19:00:00
0.85526
********************
-0.49-----0.85544--2021-08-23 19:00:00
-0.27-----0.85536--2021-08-23 20:00:00
-0.91-----0.85559--2021-08-23 21:00:00
-0.88-----0.85558--2021-08-23 22:00:00
0.41-----0.85511--2021-08-23 23:00:00
-0.52-----0.85545--2021-08-24 00:00:00
-0.96-----0.85561--2021-08-24 01:00:00
-1.24-----0.85571--2021-08-24 02:00:00
-1.43-----0.85578--2021-08-24 03:00:00
-0.96-----0.85561--2021-08-24 04:00:00
-1.15-----0.85568--2021-08-24 05:00:00
-1.02-----0.85563--2021-08-24 06:00:00
-0.14-----0.85531--2021-08-24 07:00:00
2.4699999999999998-----0.85436--2021-08-24 08:00:00
####################
SELL
2021-08-24 09:00:00
0.85436
********************
-0.85-----0.85467--2021-08-24 09:00:00
-3.65-----0.85569--2021-08-24 10:00:00
-3.13-----0.8555--2021-08-24 11:00:00
-3.21-----0.85553--2021-08-24 12:00:00
-2.66-----0.85533--2021-08-24 13:00:00
-2.5300000000000002-----0.85528--2021-08-24 14:00:00
-6.89-----0.85687--2021-08-24 15:00:00
-5.02-----0.85619--2021-08-24 16:00:00
-5.46-----0.85635--2021-08-24 17:00:00
-5.46-----0.85635--2021-08-24 17:00:00
####################
BUY
2021-08-24 17:00:00
0.8562
********************
checks
-0.41-----0.85635--2021-08-24 17:00:00
checks
-0.55-----0.8564--2021-08-24 18:00:00
checks
0.47-----0.85603--2021-08-24 19:00:00
checks
0.93-----0.85586--2021-08-24 20:00:00

In [27]:
sum(profit)

47.679999999999986

In [ ]:
sum(global_loss)

In [ ]:
conti

In [ ]:
sum(conti)

In [ ]:
len(indexB)

In [23]:
n = 0
p = 0
tn = 0
tp = 0

for i in profit:
    if i<0.0:
        n = n+i
        tn = tn+1
    else:
        p = p+i
        tp = tp+1
print(f"Total negative sm -->{n}")
print(f"Total negative -->{tn}")      
print(f"Total positive sm -->{p}")      
print(f"Total positive -->{tp}") 
print(f"Length {len(profit)}")

Total negative sm -->-55.839999999999996
Total negative -->17
Total positive sm -->103.47000000000001
Total positive -->50
Length 67

In [24]:
for i in profit:
    print(i)

1.76
1.5899999999999999
1.51
-0.03
1.02
1.8900000000000001
1.87
1.51
1.45
3.84
-5.05
2.36
1.1
1.32
1.45
2.63
2.2800000000000002
1.13
1.18
1.81
2.69
2.33
-0.82
1.95
3.4
2.88
2.14
1.81
-1.13
1.76
1.81
-0.22
1.8900000000000001
2.0
1.29
-1.67
-0.38
1.65
-0.41
1.98
-1.54
-2.22
1.43
-8.95
-1.13
1.95
1.65
2.0
2.8
6.2
4.25
-4.34
2.06
1.4
-2.5300000000000002
1.07
1.54
2.36
2.8
3.4
1.8399999999999999
-10.05
-9.91
1.76
1.21
2.4699999999999998
-5.46

In [ ]:
# plt.plot(a[-10:].smaC)
# plt.plot(a[-10:].smaO)
a['smaC'][-90:].plot(figsize=(15,6))
# rates_frame['ll'] = rates_frame['close'].rolling(window=100).mean()
a['smaO'][-90:].plot()
b['close'][-90:].plot()

# plt.plot( l[200:-100], 'r').rolling(window=100).

plt.xticks(rotation = 45)

In [ ]:
  elif check == 1:
        sell_price = a.iloc[i].close
        pp = price_action(symbol, 0.02, buy_price, sell_price,mt5.ORDER_TYPE_SELL)
        print(f"{pp}-----{a.iloc[i].close}--{a.iloc[i].name}")


        if pp > 0.0:
            check = 0
            profit.append(pp)
            index.append(pp)
            print("Greater")
        elif a.iloc[i].smaC < a.iloc[i].smaO:
            check = 0
            profit.append(pp)
            if pp > 0.0:
                index.append(pp)
            else:
                indexB.append(pp)
            print("smaC<smaO")
        elif a.iloc[i].smaC > a.iloc[i].smaO:
            check = 0
            profit.append(pp)
            if pp > 0.0:
                index.append(pp)
            else:
                indexB.append(pp)
            print("smaC>smaO")
#         i = i-2
#         print(i)

In [ ]:
#less negatives more positives
# symbol = "CADJPY"
# b= get_values1(symbol)
# b = b.dropna()
b = a
B = []
check = 0
profit = []
index = []
indexB = []
counter = 0
peck = 0
p= []
checks = 0
counterr = 0
profits = []
up = 0
rsi1 = []
rsi2 = []
mul = 100000
global_loss = []
conti = []

for i in range(2,len(a)-1):
    if a.iloc[i-1].smaC < a.iloc[i-1].smaO and check == 0:
        buy_price = b.iloc[i].open #BUY Action
        p2 = threading.Thread(target=follow, args=(i, a, buy_price, mt5.ORDER_TYPE_SELL))
        p2.start()
        print("#"*20)
        print("SELL")
        print(round(a.iloc[i-2].smaC, 6), round(a.iloc[i-2].smaO, 6), a.iloc[i-2].name)
        print(round(a.iloc[i-1].smaC, 6), round(a.iloc[i-1].smaO, 6), a.iloc[i-1].name)
        if (round(a.iloc[i-1].smaC, 6) - round(a.iloc[i-1].smaO, 6)) <  :
        
        print(round(a.iloc[i+1].smaC, 6), round(a.iloc[i+1].smaO, 6), a.iloc[i+1].name)
        
        
        
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        check = 1
        checks = 0
    elif a.iloc[i-1].smaC > a.iloc[i-1].smaO and checks == 0:
        buy_price = b.iloc[i].open #BUY Action
        p3 = threading.Thread(target=follow, args=(i, a, buy_price,mt5.ORDER_TYPE_BUY))
        p3.start()
        print("#"*20)
        print("BUY")
        print(round(a.iloc[i-1].smaC, 6), round(a.iloc[i-1].smaO, 6), a.iloc[i-1].name)
        print(a.iloc[i].name)
        print(a.iloc[i].open)
        print("*"*20)
        checks = 1
        check = 0